services:
  backend:
    image: shivam011/retail-backend
    container_name= backend
    ports:
      - 5000:5000
    restart: always
  frontend: 
    image: shivam011/retail-frontend
    container_name: frontend
    ports:
      - 80:80
    restart: always