apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudcart-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/shivamsharma20work-afk/retail-shop-gitOps'
    targetRevision: main
    path: k8s  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cloudcart
  syncPolicy:
    automated: # Ye apne aap sync karega
      prune: true
      selfHeal: true